// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWtdUUsA22TOhTEE3TuuaLOH1vViIj7k0',
    appId: '1:175578155692:web:98982d422516d471ccad09',
    messagingSenderId: '175578155692',
    projectId: 'document-reader-67be4',
    authDomain: 'document-reader-67be4.firebaseapp.com',
    storageBucket: 'document-reader-67be4.firebasestorage.app',
    measurementId: 'G-TV8PQL6CKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKYqXUyFOaC8kHzqyIlSi9EsYGcged-Xc',
    appId: '1:175578155692:android:e41e2d193e3d0a81ccad09',
    messagingSenderId: '175578155692',
    projectId: 'document-reader-67be4',
    storageBucket: 'document-reader-67be4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0oxkHVIEO5HwrGqGfqqI41XnLrn3Qo48',
    appId: '1:175578155692:ios:72143e2610083e17ccad09',
    messagingSenderId: '175578155692',
    projectId: 'document-reader-67be4',
    storageBucket: 'document-reader-67be4.firebasestorage.app',
    iosBundleId: 'com.example.allDocumentsReader',
  );
}
